# Patch for @rules_java to build singlejar from source instead of using prebuilt binaries on NixOS.
# See https://wiki.enola.dev/computer/programming/bazel/rules-java
exports_files(["rules_java_singlejar.patch"])
