# SPDX-License-Identifier: Apache-2.0
#
# Copyright 2025 The Enola <https://enola.dev> Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Ignore the (empty) WORKSPACE.bazel, only MODULE.bazel
# https://github.com/VirtusLab/bazel-steward/issues/423
# https://virtuslab.github.io/bazel-steward/docs/configuration/configuration-file/#rule-resolution
update-rules:
  - kinds: bazel-rules
    enabled: false

maven:
  # https://github.com/VirtusLab/bazel-steward/issues/401
  # https://github.com/enola-dev/enola/issues/254
  repository-name: enola_maven

pull-requests:
  - group-id: auto-service
    dependencies: "com.google.auto.service:*"
  - group-id: protobuf
    dependencies: "com.google.protobuf:*"
  - group-id: grpc
    dependencies: "io.grpc:*"
  - group-id: google-adk
    dependencies: "com.google.adk:*"
  - group-id: google-api-grpc
    dependencies: "com.google.api.grpc:*"
  - group-id: opentelemetry
    dependencies: "io.opentelemetry:*"
  - group-id: jackson
    dependencies: "com.fasterxml.jackson*:*"
  - group-id: junit5-jupiter
    dependencies: "org.junit.jupiter:*"
  - group-id: junit5-platform
    dependencies: "org.junit.platform:*"
  - group-id: maven-resolver
    dependencies: "org.apache.maven.resolver:*"
  - group-id: maveniverse
    dependencies: "eu.maveniverse*:*"
  - group-id: rdf4j
    dependencies: "org.eclipse.rdf4j:*"

  # NB: We're using ${dependencyId} instead of ${group}/${artifact} because
  #     of https://github.com/VirtusLab/bazel-steward/issues/439.
  - title: "Update ${dependencyId} from ${versionFrom} to ${versionTo}"
    commit-message: "deps: Update ${dependencyId} from ${versionFrom} to ${versionTo}"
    # NO 'kinds: maven', see https://github.com/VirtusLab/bazel-steward/issues/440

# https://virtuslab.github.io/bazel-steward/docs/configuration/configuration-file/maven.html
post-update-hooks:
  - kinds: maven
    commands:
      - "REPIN=1 bazelisk run @maven//:pin"
      - "tools/javac/dependencies.bash"
    files-to-commit:
      - "maven_install.json"
      - "docs/dev/dependencies.txt"
    run-for: commit

  # https://github.com/VirtusLab/bazel-steward/issues/422
  # TODO https://stackoverflow.com/q/79567769/421602
  - kinds: bzlmod
    commands:
      - "bazelisk sync --enable_workspace"
    files-to-commit:
      - "MODULE.bazel.lock"

  # TODO https://github.com/VirtusLab/bazel-steward/issues/426
  # - commands: "buildifier --lint=fix -r ."
  #   files-to-commit:
  #     - "**/*.bzl"
  #     - "**/BUILD"
  #     # - "**/BUILD.bazel"
  #     - "MODULE.bazel"
  #     - "MODULE.bazel.lock"
  #     # - "WORKSPACE"
  #     - "WORKSPACE.bazel"
  #   run-for: pull-request
  #   commit-message: "clean(deps): Buildifieraroo"
