version = 1

test_patterns=["**/*Test.java", "**/Test*.java", "**/*.test.ts"]

exclude_patterns = [
  "dist/**",
  "node_modules/**,",
  "web-out/**",
]

[[analyzers]]
name = "java"

  [analyzers.meta]
  # https://docs.deepsource.com/docs/analyzers-java#runtime_version
  runtime_version = "21"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "javascript"
