version = 1

# TODO How to add configuration to ignore e.g. JAVA-W1035 here?
#   - https://discuss.deepsource.com/t/java-w1035-java-analyzer-is-broken-for-java-14-records/709/1
#   - https://discuss.deepsource.com/t/deepsource-toml-should-allow-ignoring-issues/710

test_patterns=["**/*Test.java", "**/Test*.java", "**/*.test.ts"]

exclude_patterns = [
  "dist/**",
  "node_modules/**,",
  "web-out/**",
]

[[analyzers]]
name = "java"

  [analyzers.meta]
  # https://docs.deepsource.com/docs/analyzers-java#runtime_version
  runtime_version = "21"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  skip_doc_coverage = ["arrow-function-expression", "class-declaration", "class-expression", "function-declaration", "function-expression", "method-definition"]
