version = 1

test_patterns=["**/*Test.java"]

[[analyzers]]
name = "java"

  [analyzers.meta]
  # https://docs.deepsource.com/docs/analyzers-java#runtime_version
  runtime_version = "19"

[[analyzers]]
name = "shell"
