# SPDX-License-Identifier: Apache-2.0
#
# Copyright 2023-2026 The Enola <https://enola.dev> Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

$schema: https://raw.githubusercontent.com/DavidAnson/markdownlint/v0.37.4/schema/markdownlint-config-schema.json
# https://github.com/DavidAnson/markdownlint#optionsconfig
# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml

# Beware, there are several project, and GitHub repos, named something like Markdown Lint.
# This project uses https://github.com/DavidAnson/markdownlint, via .pre-commit-config.yaml
# (as well as the DavidAnson.vscode-markdownlint in .vscode/settings.json, or other IDEs;
# TODO figure out how configure IntelliJ for markdownlint...
# but https://github.com/Strajk/intellij-plugin-markdownlint does not look great).
#
# The following are OTHER confusingly similarly named tools, which this project does NOT use:
#   - https://github.com/markdownlint/markdownlint
#   - https://github.com/updownpress/markdown-lint

default: true

MD007:
  # mkdocs (Material) apparently works with "standard" (common?) 2 indent in some cases, but not others
  # (the exact rule when it works and when it does not is not clear, to me; but never mind). However, it
  # always formats nested unordered lists correctly when using 4 indents - so we enforce that.
  start_indented: false
  indent: 4

MD013:
  # Must match .editorconfig [*.md] max_line_length
  # This 4096 means "unlimited" (unset) - essentially https://github.com/DavidAnson/markdownlint/issues/298.
  # Until https://github.com/DavidAnson/markdownlint/issues/535 is available,
  # it's not feasible to set this - just too PITA, while writing docs.
  #
  # One possible avenue to enable fixing automatic reflow formatting could be
  # to enable Prettier to format MD (by removing *.md from .prettierignore).
  # This ALMOST works, but in Prettier v2.8.4 just has some issues:
  #   A. Breaks code blocks inside 1. 1. 1. OL; see https://github.com/prettier/prettier/issues/13175
  #   B. Replaces '*' with '-' for UL; not my preference, but is likely intentional,
  #      given https://prettier.io/docs/en/option-philosophy.html.
  #   C. It over-indents '-' causing MD030; see https://github.com/prettier/prettier/issues/5299
  #      and https://github.com/prettier/prettier/pull/5306 or https://github.com/prettier/prettier/pull/13987 ?
  # Another avenue would be to look into a different MD formatter than Prettier,
  # perhaps remark directly ... but that seems a bit overkill, for now.
  line_length: 4096
  code_blocks: true
  code_block_line_length: 4096
  strict: false
  stern: false

# Allow headings ending in '!'
MD026:
  punctuation: ",;:。，；："

# Allow <sub> but no other inline HTML in source MD
MD033:
  allowed_elements:
    - "br"
    - "sub"
    - "script"
    - "iframe"

# Bare URL are OK
MD034: false

# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md046---code-block-style
# style: "indented" prevents setting code block language
# style: "fenced" enforces ``` and thus prevents indenting, which is nicer to read in raw ASCII where possible
# style: "consistent" prevents mixing indenting (without code block language) and fenced with code block language.
MD046: false
