arrowParens: avoid
bracketSameLine: true
bracketSpacing: true
proseWrap: always
quoteProps: as-needed
semi: false
singleAttributePerLine: true
singleQuote: false
trailingComma: "es5"
# Note that printWidth, useTabs, tabWidth, endOfLine is read from .editorconfig by Prettier
