lint:
  rules:
    all_default: true
    remove:
      - MAX_LINE_LENGTH # https://github.com/yoheimuta/protolint/issues/103
      - FILE_HAS_COMMENT
      - MESSAGES_HAVE_COMMENT
      - SERVICES_HAVE_COMMENT
      - RPCS_HAVE_COMMENT
      - FIELDS_HAVE_COMMENT
      - ENUMS_HAVE_COMMENT
      - ENUM_FIELDS_HAVE_COMMENT
