# SPDX-License-Identifier: Apache-2.0
#
# Copyright 2023-2024 The Enola <https://enola.dev> Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Read https://github.com/enola-dev/enola/issues/180 for background...

# This builds a container image for an Enola development environment.
# It may later be referenced in .devcontainer/devcontainer.json, but can
# also be used unrelated to https://containers.dev e.g. for local builds
# by the ./devenv script.

# TODO The https://containers.dev base image don't work on plain Debian...
# This is a "fat" container with a lot of ready tools
# from https://github.com/devcontainers/images/tree/main/src/universal
# (Note that "image": "mcr.microsoft.com/devcontainers/base:bookworm"
#  from https://github.com/devcontainers/images/tree/main/src/base-debian
#  from https://github.com/devcontainers/templates/tree/main/src/debian
#  is very (too) minimal, and we would need to add a lot...)
# FROM mcr.microsoft.com/devcontainers/universal:2-linux
FROM docker.io/library/fedora:39

RUN dnf update -y

RUN dnf install -y fish gcc-c++ golang \
    java-21-openjdk-devel java-21-openjdk-src java-21-openjdk-javadoc \
    java-21-openjdk-javadoc-zip java-21-openjdk-jmods

# TODO useradd --shell fish ...
RUN useradd "developer" && \
    sed -i 's/# %wheel/%wheel/' /etc/sudoers && \
    sudo usermod -aG wheel "developer"
USER developer

# https://go.dev/doc/install (adapted for Fedora, which does not use ~/.profile, and ignores PATH in ~/.bash_profile)
RUN echo "export PATH=$PATH:/home/developer/go/bin" >> /home/developer/.bashrc

# It's a bit dumb that we have a manually maintained list of "essential initial dev env set-up" files here...
# An alternative could be to use 'RUN --mount=type=bind,source=.,target=/workspace/', but this has been
# observed to work inconsistently between older/newer Docker versions, as well as with Podman on Fedora
# (see https://github.com/enola-dev/enola/issues/515), so let's just do it like this, unless someone
# reading this has a better idea! [Note that it only makes sense to "pre-warm" tools that end up in
# $HOME; but any tools in the "repo" (/workspace) cannot be pre-loaded, as the $PWD mount hides it.

ADD tools /workspace/tools
ADD .tool-versions /workspace/
ADD .bazel* /workspace/
ADD WORKSPACE* /workspace/
ADD MODULE* /workspace/
ADD BUILD /workspace/
ADD maven_install.json /workspace/

WORKDIR /workspace/
RUN /workspace/tools/devenv/install.bash

# See https://docs.docker.com/build/guide/mounts/ for documentation about --mount=type.
