#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Copyright 2023 The Enola <https://enola.dev> Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

# This launch script should work whatever the current working directory is;
# for both sub-directories of the project, as well as if it's anywhere else.
# (This is handy e.g. when invoking it on models files that are stored outside of this project.)

CWD=$(pwd)
ROOT="$(realpath "$(dirname "$0")")"

cd "$ROOT"
LOG=$(mktemp)

if [ -x "$(command -v hashdir)" ]; then
  mkdir -p "$ROOT"/.cache
  mv "$ROOT"/.cache/java.hash "$ROOT"/.cache/java.hash.previous 2>/dev/null || true
  hashdir --quiet java/ > "$ROOT"/.cache/java.hash
  set +e
  diff "$ROOT"/.cache/java.hash "$ROOT"/.cache/java.hash.previous 2>/dev/null
  DIFF="$?"
  set -e
else
  DIFF=3
fi

if [ "$DIFF" -ne 0 ]; then
  tools/distro/build-execjar.bash >"$LOG" 2>&1
  exit_code="$?"
  rm "$LOG"
else
  exit_code=0
fi

if [[ "$exit_code" == "0" ]]; then
  source "$ROOT"/tools/bazel-java-tool-chain/bazel-java-tool-chain.bash
  JAVA=$(java_home)
  PATH="$JAVA"/bin:"$PATH" site/download/latest/enola "$@"

else
  cat "$LOG" && echo >&2 && echo >&2
  rm "$LOG"
  cd "$CWD"
  exit "$exit_code"
fi
