#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Copyright 2023 The Enola <https://enola.dev> Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

# This launch script should work whatever the current working directory is;
# for both sub-directories of the project, as well as if it's anywhere else.
# (This is handy e.g. when invoking it on models files that are stored outside of this project.)

ROOT="$(dirname "$(realpath "$0")")"

if [ -x "$(command -v hashdir)" ]; then
  mkdir -p "$ROOT"/.cache
  mv "$ROOT"/.cache/java.hash "$ROOT"/.cache/java.hash.previous 2>/dev/null || true
  # TODO Replace (Python) hashdir with my own (Java) tool, see https://docs.enola.dev/use/info/#digest
  {
    hashdir --quiet "$ROOT"/java/
    # https://github.com/enola-dev/enola/issues/1901
    hashdir --quiet "$ROOT"/generated/protoc/java
    hashdir --quiet "$ROOT"/models/
    hashdir --quiet "$ROOT"/web/
    sha512sum "$ROOT/MODULE.bazel"
  } >"$ROOT"/.cache/java.hash
  set +e
  diff "$ROOT"/.cache/java.hash "$ROOT"/.cache/java.hash.previous >/dev/null 2>/dev/null
  DIFF="$?"
  set -e
else
  DIFF=3
fi

LOG=$(mktemp)
if [ "$DIFF" -ne 0 ] || [ ! -f "$ROOT"/site/download/latest/enola.jar ]; then
  set +e
  echo "Input hash changed, re-building enola.jar..."
  "$ROOT"/tools/distro/build-execjar.bash >"$LOG" 2>&1
  exit_code="$?"
  set -e
else
  exit_code=0
  rm "$LOG"
fi

if [[ "$exit_code" == "0" ]]; then
  # TODO Remove TERM override after https://github.com/jline/jline3/issues/1259 is fixed
  TERM=xterm-256color java -jar "$ROOT"/site/download/latest/enola.jar "$@"

else
  cat "$LOG" && echo >&2 && echo >&2
  rm "$LOG"
  exit "$exit_code"
fi
