#!/usr/bin/env bash

set -euxo pipefail

# Find flox (while PATH is still available)
FLOX=$(which flox)

# Clear PATH!
PATH=

# NOT source tools/flox
$FLOX activate --mode=run

echo "Now source ./test.bash ..."
source ./test.bash

# TODO or use something like:
#   env -i flox activate -- source
