#
# SPDX-License-Identifier: Apache-2.0
#
# Copyright 2023 The Enola <https://enola.dev> Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# proto-file: dev/enola/core/enola_core.proto
# proto-message: Entity

# TODO Merge this with foo-abc.textproto into 1 single file

id {
  ns: "demo"
  entity: "bar"
  paths: ["abc", "def"]
}
href {
  key: "wiki"
  value: "https://en.wikipedia.org/w/index.php?fulltext=Search&search={def}"
}
related {
  key: "one"
  value: {
    ns: "demo"
    entity: "baz"
    paths: "uvw"
  }
}
