# SPDX-License-Identifier: Apache-2.0
#
# Copyright 2023 The Enola <https://enola.dev> Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# https://protobuf.dev/reference/protobuf/textformat-spec/
# proto-file: dev/enola/core/enola_model.proto
# proto-message: Model

scheme: "demo"
entities {
  id: "foo"
  label: "Fo-o"
  emoji: "💂"
  doc_url: "demo-model.md#foo"
  proto_fqn: "dev.enola.demo.Foo"
  query {
    key: "name",
    value: {}
  }
}
entities {
  id: "bar"
  label: "Bar (not Bard)"
  emoji: "👩‍🎤"
  doc_url: "demo-model.md#bar"
  proto_fqn: "dev.enola.demo.Bar"
  query {
    key: "name",
    value: {}
  }
  query {
    key: "foo",
    value: { ref_id_template: "demo:foo?name={query.foo}" }
  }
  related {
    key: "one",
    value: {
      label: "Primary Baz",
      rel_id_template: "demo:baz?uuid={proto.something.id}",
      depends: true
    }
  }
  related {
    key: "two",
    value: {
      label: "Secondary Baz",
      rel_id_template: "demo:baz?uuid={proto.otherthing.id}"
    }
  }
  url {
    key: "wiki",
    value: {
      label: "Wikipedia",
      description: "founded by Jimmy Wales",
      url_template: "https://en.wikipedia.org/w/"
                    "index.php?fulltext=Search&search={name}"
    }
  }
}
entities {
  id: "baz"
  query {
    key: "uuid",
    value: {}
  }
}
