# https://protobuf.dev/reference/protobuf/textformat-spec/
# proto-file: dev/enola/core/enola_model.proto
# proto-message: Model

scheme: "demo"
entity {
  id: "foo"
  label: "Fo-o"
  emoji: "💂"
  doc_url: "demo-model.md#foo"
  proto_fqn: "dev.enola.demo.Foo"
  query { key: "name", value: { } }
}
entity {
  id: "bar"
  label: "Bar (not Bard)"
  emoji: "👩‍🎤"
  doc_url: "demo-model.md#bar"
  proto_fqn: "dev.enola.demo.Bar"
  query { key: "name", value: { } }
  query { key: "foo", value: { ref_id_template: "demo:foo?name={query.foo}" } }
  related { key: "one", value: { label: "Primary Baz", rel_id_template: "demo:baz?uuid={proto.something.id}", depends_on: true } }
  related { key: "two", value: { label: "Secondary Baz", rel_id_template: "demo:baz?uuid={proto.otherthing.id}" } }
  url { key: "wiki", value: { label: "Wikipedia", description: "founded by Jimmy Wales", url_template: "https://en.wikipedia.org/w/index.php?fulltext=Search&search={name}" } }
}
entity {
  id: "baz"
  query { key: "uuid", value: { } }
}
