## Flox Environment Manifest -----------------------------------------
##
##   _Everything_ you need to know about the _manifest_ is here:
##
##               https://flox.dev/docs/concepts/manifest
##
## -------------------------------------------------------------------
# Flox manifest version managed by Flox CLI
version = 1


## Install Packages --------------------------------------------------
##  $ flox install gum  <- puts a package in [install] section below
##  $ flox search gum   <- search for a package
##  $ flox show gum     <- show all versions of a package
## -------------------------------------------------------------------
[install]
# TODO Replace "python312" with just "python3" once
# https://github.com/linkml/linkml/issues/2563 is fixed
# with https://github.com/linkml/linkml/pull/2358,
# for https://github.com/linkml/linkml/issues/2357;
# see https://github.com/enola-dev/enola/pull/1227.
python3 = { pkg-path = "python312" }

## Environment Variables ---------------------------------------------
##  ... available for use in the activated environment
##      as well as [hook], [profile] scripts and [services] below.
## -------------------------------------------------------------------
[vars]
# INTRO_MESSAGE = "It's gettin' Flox in here"


## Activation Hook ---------------------------------------------------
##  ... run by _bash_ shell when you run 'flox activate'.
## -------------------------------------------------------------------
[hook]
on-activate = '''
  # Autogenerated by Flox

  # Setup a Python virtual environment

  export PYTHON_DIR="$FLOX_ENV_CACHE/python"
  if [ ! -d "$PYTHON_DIR" ]; then
    echo "Creating python virtual environment in $PYTHON_DIR"
    python -m venv "$PYTHON_DIR"
  fi

  # Activate venv and install packages in a subshell so
  # that the venv can be freshly activated in the profile section.
  # (The --quiet flag originally proposed by Flox was removed, for clarity.)
  (
    source "$PYTHON_DIR/bin/activate"
    pip install -r "$FLOX_ENV_PROJECT/requirements.txt"
  )

  # End autogenerated by Flox
'''


## Profile script ----------------------------------------------------
## ... sourced by _your shell_ when you run 'flox activate'.
## -------------------------------------------------------------------
[profile]
bash = '''
  # Autogenerated by Flox

  echo "Activating python virtual environment" >&2
  source "$PYTHON_DIR/bin/activate"

  # End autogenerated by Flox
'''
fish = '''
  # Autogenerated by Flox

  echo "Activating python virtual environment" >&2
  source "$PYTHON_DIR/bin/activate.fish"

  # End autogenerated by Flox
'''
tcsh = '''
  # Autogenerated by Flox

  echo "Activating python virtual environment" >&2
  source "$PYTHON_DIR/bin/activate.csh"

  # End autogenerated by Flox
'''
zsh = '''
  # Autogenerated by Flox

  echo "Activating python virtual environment" >&2
  source "$PYTHON_DIR/bin/activate"

  # End autogenerated by Flox
'''


## Services ----------------------------------------------------------
##  $ flox services start             <- Starts all services
##  $ flox services status            <- Status of running services
##  $ flox activate --start-services  <- Activates & starts all
## -------------------------------------------------------------------
[services]
# myservice.command = "python3 -m http.server"


## Other Environment Options -----------------------------------------
[options]
# Systems that environment is compatible with
systems = [
  "aarch64-darwin",
  "aarch64-linux",
  "x86_64-darwin",
  "x86_64-linux",
]
# Uncomment to disable CUDA detection.
# cuda-detection = false
