#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Copyright 2023-2025 The Enola <https://enola.dev> Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

# This script publishes https://docs.enola.dev/demo/
# It is intended to be run by tools/docs/build.bash, which also builds the docs.

dist=$(dirname "$0")/web-out/bundle/
demo=$(dirname "$0")/../site/demo/
rm -rf "$demo"
mkdir -p "$demo"

if [[ ! -d "$dist" || ! "$(ls -A "$dist")" ]]; then
  echo "Error: '$dist' does not exist, or is empty? Run web/build!" >&2
  exit 1
fi

cp -r "$dist"/* "$demo"
